default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: blog_rubyonrails_guide_development
test:
  <<: *default
  database: blog_rubyonrails_guide_test

production:
  <<: *default
  database: blog_rubyonrails_guide_production
  username: blog_rubyonrails_guide
  password: <%= ENV['BLOG_RUBYONRAILS_GUIDE_DATABASE_PASSWORD'] %>
